// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace FactoryAPI.Models;

public partial class FactoryDatabaseContext : DbContext
{
    public FactoryDatabaseContext(DbContextOptions<FactoryDatabaseContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Item> Items { get; set; }
}